version: '2.1'

volumes:
   wagtaildb:
        driver: local

services:

  web:
    image: ${REGISTRY}optimum/cms:wagtail-1.13.5-s
    container_name: wagtail_web
    restart: always
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
    volumes:
      - ./supervisord/wagtail.conf:/etc/supervisor/conf.d/wagtail.conf
      - ./configs/backend/wsgi.ini:/etc/wagtail-wsgi.ini
      - ./configs/backend/production.py:/app/app/settings/production.py
      - ./configs/backend/dev.py:/app/app/settings/dev.py
      - ./configs/backend/base.py:/app/app/settings/base.py
      - ./configs/backend/create_admin.py:/app/create_admin.py
    links:
     - postgres
     - elasticsearch
    ports:
     - "8000"
    env_file: .env

  postgres:
    container_name: wagtail_db
    image: postgres
    restart: always
    ports:
     - "5432"
    env_file: .env
    volumes:
      - wagtaildb:/var/lib/postgresql/data/pgdata

  elasticsearch:
    container_name: wagtail_search
    restart: always
    image: orchardup/elasticsearch
    ports:
      - "127.0.0.1:9200:9200"

  nginx:
    image: ${REGISTRY}optimum/nginx-le:stable
    container_name: wagtail_nginx
    restart: always
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs/ssl:/etc/nginx/ssl
      - ./certs/letsencrypt:/etc/letsencrypt
      - ./cron/nginx:/var/spool/cron/crontabs
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./supervisord/nginx.conf:/etc/supervisor/conf.d/nginx.conf
    links:
      - web
    depends_on:
      - web
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
